# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0

    working_directory: ~/repo

    steps:
      - checkout
      - python --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m virtualenv -p=python3.8 venv;
            . venv/bin/activate;
            pip install --upgrade pip;
            pip install -r requirements.txt;
            pip install -e .
            
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create topology cnn
          command: |
            mkdir ./DATASETS;
            printf "Input(28,28,1);\nConv(32,5,tanh);\nPool(2,max);\nConv(64,3,relu);\nBatchNorm();\nPool(2,max);\nDropout(0.25);\nConv(128,2,tanh);\nPool(2,max);\nFc(1024,relu);\nBatchNorm();\nDropout(0.5);\nFc(10,softmax);">top.txt;
      - store_artifacts:
          path: ~/repo/.DATASETS
      
      - store_artifacts:
          path: top.txt
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python nntool/tests/test_simple.py

workflows:
  version: 2
  workflow:
    jobs:
      - build
